<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29765" started-at="2018-12-04T15:24:54Z" finished-at="2018-12-04T15:25:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29765" started-at="2018-12-04T15:24:54Z" finished-at="2018-12-04T15:25:24Z">
      <class name="com.dms.qa.testcases.UserManagementPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="5797" started-at="2018-12-04T20:54:54Z" finished-at="2018-12-04T20:55:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateCreateNewUserManagement(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="validateCreateNewUserManagement" duration-ms="1998" started-at="2018-12-04T20:55:00Z" data-provider="getDMSTestData" finished-at="2018-12-04T20:55:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test78353]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Hari]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[hari@esoftech.org]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Administrator]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[dgsg]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User is not able to added- user already exists expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User is not able to added- user already exists expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.dms.qa.testcases.UserManagementPageTest.validateCreateNewUserManagement(UserManagementPageTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewUserManagement -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2018-12-04T20:55:02Z" finished-at="2018-12-04T20:55:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="4250" started-at="2018-12-04T20:55:05Z" finished-at="2018-12-04T20:55:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateCreateNewUserManagement(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="validateCreateNewUserManagement" duration-ms="1961" started-at="2018-12-04T20:55:09Z" data-provider="getDMSTestData" finished-at="2018-12-04T20:55:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ghhfasgf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[fgh]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dsgsg@gmail.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Administrator]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[gjf]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User is not able to added- user already exists expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User is not able to added- user already exists expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.dms.qa.testcases.UserManagementPageTest.validateCreateNewUserManagement(UserManagementPageTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewUserManagement -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2018-12-04T20:55:11Z" finished-at="2018-12-04T20:55:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="4240" started-at="2018-12-04T20:55:14Z" finished-at="2018-12-04T20:55:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateCreateNewUserManagement(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="validateCreateNewUserManagement" duration-ms="1925" started-at="2018-12-04T20:55:19Z" data-provider="getDMSTestData" finished-at="2018-12-04T20:55:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[rffyry]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[123456.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hh]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dgfgh@gmail.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[NA]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Administrator]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[gfdh]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User is not able to added- user already exists expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User is not able to added- user already exists expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.dms.qa.testcases.UserManagementPageTest.validateCreateNewUserManagement(UserManagementPageTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewUserManagement -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dms.qa.testcases.UserManagementPageTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2018-12-04T20:55:21Z" finished-at="2018-12-04T20:55:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.dms.qa.testcases.UserManagementPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
